### ISSUE TITLE
KeyError: 'coco_url'

### ISSUE THREAD

**Issue by Siddhijain16** [CasiaFan/Dataset_to_VOC_converter#23]
I am trying to convert dataset  from coco to voc format using anno_coco2voc.py file but got this KeyError: 'coco_url'

billion@billion-Inspiron-3542:~/Dataset_to_VOC_converter$ python3 anno_coco2voc.py --anno_file /home/billion/Desktop/Siddhi/document_edge_detection_dataset/earlier_training/testing/test.json \
>                          --type instance \
>                          --output_dir /home/billion/Desktop/Siddhi/document_edge_detection_dataset/earlier_training/annotations
Traceback (most recent call last):
  File "anno_coco2voc.py", line 154, in <module>
    main(args)
  File "anno_coco2voc.py", line 143, in main
    parse_instance(content, args.output_dir)
  File "anno_coco2voc.py", line 60, in parse_instance
    anno_tree = instance2xml_base(groups[0])
  File "anno_coco2voc.py", line 16, in instance2xml_base
    E.url(anno['coco_url'])
KeyError: 'coco_url'

![crop1](https://user-images.githubusercontent.com/46879959/103026958-fe514e00-457a-11eb-883a-6ed954e2b1bd.png)

**Comment by GarryJAY502** [comment]
have you solve it?

**Comment by GarryJAY502** [comment]
> 

have you solve it
